#!/bin/bash
set -e
echo "=========================================="
echo "  ISHA-X EDR — Codespace Setup"
echo "=========================================="

WORKSPACE=$(pwd)

# ---- Python: backend deps ----
echo "[1/4] Installing Python backend dependencies..."
pip3 install -q -r "$WORKSPACE/server/backend/requirements.txt"

# ---- Python: pipeline deps ----
echo "[2/4] Installing Python pipeline dependencies..."
pip3 install -q -r "$WORKSPACE/server/pipeline/requirements.txt" 2>/dev/null || true

# ---- Node: frontend ----
echo "[3/4] Installing Node.js frontend dependencies..."
cd "$WORKSPACE/server/frontend" && npm install --silent && cd "$WORKSPACE"

# ---- Auto-build .env from Codespace Secrets ----
echo "[4/4] Building .env from Codespace secrets..."
ENV_FILE="$WORKSPACE/server/backend/.env"

# Generate SESSION_SECRET if not set
if [ -z "$SESSION_SECRET" ]; then
  SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
fi

cat > "$ENV_FILE" << EOF
# Auto-generated by .devcontainer/setup.sh — DO NOT COMMIT
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
SESSION_SECRET=${SESSION_SECRET}
SERVER_HOST=agents.weknows.me
MULTI_TENANT=1
TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY:-}
WAZUH_API_BASE=https://localhost:55000
WAZUH_API_USER=wazuh
WAZUH_API_PASS=wazuh
FRONTEND_ORIGIN=https://weknows.me
EDR_RETENTION_DAYS=30
EOF

echo "  → .env written at $ENV_FILE"

# Check what's missing
MISSING=()
[ -z "$GOOGLE_CLIENT_ID" ]     && MISSING+=("GOOGLE_CLIENT_ID")
[ -z "$GOOGLE_CLIENT_SECRET" ] && MISSING+=("GOOGLE_CLIENT_SECRET")
[ -z "$TAILSCALE_AUTH_KEY" ]   && MISSING+=("TAILSCALE_AUTH_KEY")

if [ ${#MISSING[@]} -gt 0 ]; then
  echo ""
  echo "  ⚠ Missing Codespace Secrets:"
  for m in "${MISSING[@]}"; do
    echo "    - $m"
  done
  echo ""
  echo "  → Go to: github.com/settings/codespaces → Secrets"
  echo "  → Add missing secrets, then: Codespaces → Rebuild Container"
fi

# ---- Clean leftover build dirs ----
find /tmp -maxdepth 1 -name "ishax_build_*" -type d -exec rm -rf {} + 2>/dev/null || true

echo ""
echo "✓ Setup complete!"
echo ""
echo "  Run: bash server/start_linux.sh"
echo ""
